theme: jekyll-theme-architect
title: Interaction detection
description: Detecting touch & sight interaction. Built by Alon Melamud, Itamar Shenhar, Gil Maman in Haifa univercity image proccessing course.
